### PR TITLE
fix for Zygote and ChainRules OneElement

### LINKED ISSUE #1016: scalar indexing of gpu array in Zygote gradient
From Flux's test suite. This is issue https://github.com/FluxML/Zygote.jl/issues/1005

```julia
using MLDataDevices, CUDA, cuDNN, Zygote
CUDA.allowscalar(false)

cpu = cpu_device()
gpu = gpu_device()

gradient(x -> cpu(2 .* gpu(x))[1], Float32[1,2,3])[1] # error
gradient(x -> cpu(gpu(x) * gpu(x))[1,2], Float32[1 2 3; 4 5 6; 7 8 9])[1] # error
```
For the first gradient the error is 
```julia
ERROR: Scalar indexing is disallowed.
Invocation of getindex resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore should be avoided.

If you want to allow scalar iteration, use `allowscalar` or `@allowscalar`
to enable scalar iteration globally or for the operations in question.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] errorscalar(op::String)
    @ GPUArraysCore ~/.julia/packages/GPUArraysCore/GMsgk/src/GPUArraysCore.jl:155
  [3] _assertscalar(op::String, behavior::GPUArraysCore.ScalarIndexing)
    @ GPUArraysCore ~/.julia/packages/GPUArraysCore/GMsgk/src/GPUArraysCore.jl:128
  [4] assertscalar(op::String)
    @ GPUArraysCore ~/.julia/packages/GPUArraysCore/GMsgk/src/GPUArraysCore.jl:116
  [5] getindex
    @ ~/.julia/packages/GPUArrays/qt4ax/src/host/indexing.jl:50 [inlined]
  [6] first
    @ ./abstractarray.jl:452 [inlined]
  [7] dot(x::ChainRules.OneElement{Float32, 1, Tuple{Int64}, Tuple{Base.OneTo{…}}}, y::CuArray{Float32, 1, CUDA.DeviceMemory})
    @ LinearAlgebra ~/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/LinearAlgebra/src/generic.jl:894
  [8] #568
    @ ~/.julia/packages/ChainRules/vdf7M/src/rulesets/Base/arraymath.jl:108 [inlined]
  [9] unthunk
    @ ~/.julia/packages/ChainRulesCore/6Pucz/src/tangent_types/thunks.jl:205 [inlined]
 [10] wrap_chainrules_output
    @ ~/.julia/packages/Zygote/NRp5C/src/compiler/chainrules.jl:110 [inlined]
 [11] map
    @ ./tuple.jl:357 [inlined]
 [12] wrap_chainrules_output
    @ ~/.julia/packages/Zygote/NRp5C/src/compiler/chainrules.jl:111 [inlined]
 [13] ZBack
    @ ~/.julia/packages/Zygote/NRp5C/src/compiler/chainrules.jl:212 [inlined]
 [14] (::Zygote.var"#3852#back#1233"{Zygote.ZBack{…}})(Δ::ChainRules.OneElement{Float32, 1, Tuple{…}, Tuple{…}})
    @ Zygote ~/.julia/packages/ZygoteRules/M4xmc/src/adjoint.jl:72
 [15] #184
    @ ./REPL[4]:1 [inlined]
 [16] (::Zygote.Pullback{Tuple{…}, Tuple{…}})(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/NRp5C/src/compiler/interface2.jl:0
 [17] (::Zygote.var"#78#79"{Zygote.Pullback{Tuple{…}, Tuple{…}}})(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/NRp5C/src/compiler/interface.jl:91
 [18] gradient(f::Function, args::Vector{Float32})
    @ Zygote ~/.julia/packages/Zygote/NRp5C/src/compiler/interface.jl:148
 [19] top-level scope
    @ REPL[4]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by CarloLucibello**
Port of https://github.com/LuxDL/MLDataDevices.jl/pull/92
Fix #1016

### CODE REVIEW

File: lib/MLDataDevices/ext/MLDataDevicesChainRulesExt.jl [hunk 1]
```diff
@@ -0,0 +1,19 @@
+module MLDataDevicesChainRulesExt
+
+using Adapt: Adapt
+using MLDataDevices: CPUDevice, CUDADevice, AMDGPUDevice, MetalDevice,OneAPIDevice, ReactantDevice
```
Comment (avik-pal) [inline lib/MLDataDevices/ext/MLDataDevicesChainRulesExt.jl:4]:
```suggestion
using MLDataDevices: CPUDevice, CUDADevice, AMDGPUDevice, MetalDevice, oneAPIDevice, ReactantDevice
```

File: lib/MLDataDevices/ext/MLDataDevicesChainRulesExt.jl [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+using ChainRules: OneElement
+
+Adapt.adapt_storage(::CPUDevice, x::OneElement) = x
+
+for Dev in (CUDADevice, AMDGPUDevice, MetalDevice, OneAPIDevice, ReactantDevice)
```
Comment (avik-pal) [inline lib/MLDataDevices/ext/MLDataDevicesChainRulesExt.jl:9]:
```suggestion
for Dev in (CUDADevice, AMDGPUDevice, MetalDevice, oneAPIDevice, ReactantDevice)
```

File: lib/MLDataDevices/ext/MLDataDevicesZygoteExt.jl [hunk 3]
```diff
@@ -1,10 +1,20 @@
 module MLDataDevicesZygoteExt
 
 using Adapt: Adapt
-using MLDataDevices: AbstractDevice, CPUDevice
+using MLDataDevices: CPUDevice, CUDADevice, AMDGPUDevice, MetalDevice, OneAPIDevice, ReactantDevice
```
Comment (avik-pal) [inline lib/MLDataDevices/ext/MLDataDevicesZygoteExt.jl:4]:
```suggestion
using MLDataDevices: CPUDevice, CUDADevice, AMDGPUDevice, MetalDevice, oneAPIDevice, ReactantDevice
```

File: lib/MLDataDevices/ext/MLDataDevicesZygoteExt.jl [hunk 4]
```diff
@@ -1,10 +1,20 @@
...
 using Zygote: OneElement
 
-Adapt.adapt_structure(::CPUDevice, x::OneElement) = x
-Adapt.adapt_structure(to::AbstractDevice, x::OneElement) = Adapt.adapt(to, collect(x))
+Adapt.adapt_storage(::CPUDevice, x::OneElement) = x
 
+for Dev in (CUDADevice, AMDGPUDevice, MetalDevice, OneAPIDevice, ReactantDevice)
```
Comment (avik-pal) [inline lib/MLDataDevices/ext/MLDataDevicesZygoteExt.jl:9]:
```suggestion
for Dev in (CUDADevice, AMDGPUDevice, MetalDevice, oneAPIDevice, ReactantDevice)
```

File: lib/MLDataDevices/ext/MLDataDevicesChainRulesExt.jl [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+    # use `@eval` to avoid ambiguity with adapt_storage(::CUDADevice, ::AbstractArray)
+    @eval Adapt.adapt_storage(to::$Dev, x::OneElement) = Adapt.adapt(to, collect(x))
+end
+
+for Dev in (CUDADevice, AMDGPUDevice)
+    # use `@eval` to avoid ambiguity with adapt_storage(::CUDADevice{Nothing}, ::AbstractArray)
+    @eval Adapt.adapt_storage(to::$Dev, x::OneElement) = Adapt.adapt(to, collect(x))
```
Comment (avik-pal) [inline lib/MLDataDevices/ext/MLDataDevicesChainRulesExt.jl:16]:
```suggestion
    @eval Adapt.adapt_storage(to::$Dev{Nothing}, x::OneElement) = Adapt.adapt(to, collect(x))
```

**Review by avik-pal — CHANGES_REQUESTED** [review]

File: lib/MLDataDevices/ext/MLDataDevicesChainRulesExt.jl [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+
+for Dev in (CUDADevice, AMDGPUDevice, MetalDevice, oneAPIDevice, ReactantDevice)
+    # use `@eval` to avoid ambiguity with adapt_storage(::CUDADevice, ::AbstractArray)
+    @eval Adapt.adapt_storage(to::$Dev, x::OneElement) = Adapt.adapt(to, collect(x))
+end
+
+for Dev in (CUDADevice, AMDGPUDevice)
+    # use `@eval` to avoid ambiguity with adapt_storage(::CUDADevice{Nothing}, ::AbstractArray)
+    @eval Adapt.adapt_storage(to::$Dev{Nothing}, x::OneElement) = Adapt.adapt(to, collect(x))
+end
```
Comment (avik-pal) [inline lib/MLDataDevices/ext/MLDataDevicesChainRulesExt.jl:17]:
```suggestion
for dev in (CUDADevice, AMDGPUDevice, MetalDevice, oneAPIDevice, ReactantDevice,
        CUDADevice{Nothing}, AMDGPUDevice{Nothing})
    # use `@eval` to avoid ambiguity with adapt_storage(::CUDADevice, ::AbstractArray)
    @eval Adapt.adapt_storage(to::$(dev), x::OneElement) = Adapt.adapt(to, collect(x))
end
```

File: lib/MLDataDevices/ext/MLDataDevicesZygoteExt.jl [hunk 7]
```diff
@@ -1,10 +1,20 @@
...
 
+for Dev in (CUDADevice, AMDGPUDevice, MetalDevice, oneAPIDevice, ReactantDevice)
+    # use `@eval` to avoid ambiguity with adapt_storage(::CUDADevice, ::AbstractArray)
+    @eval Adapt.adapt_storage(to::$Dev, x::OneElement) = Adapt.adapt(to, collect(x))
 end
+
+for Dev in (CUDADevice, AMDGPUDevice)
+    # use `@eval` to avoid ambiguity with adapt_storage(::CUDADevice{Nothing}, ::AbstractArray)
+    @eval Adapt.adapt_storage(to::$Dev{Nothing}, x::OneElement) = Adapt.adapt(to, collect(x))
+end
```
Comment (avik-pal) [inline lib/MLDataDevices/ext/MLDataDevicesZygoteExt.jl:17]:
```suggestion
for dev in (CUDADevice, AMDGPUDevice, MetalDevice, oneAPIDevice, ReactantDevice,
        CUDADevice{Nothing}, AMDGPUDevice{Nothing})
    # use `@eval` to avoid ambiguity with adapt_storage(::CUDADevice, ::AbstractArray)
    @eval Adapt.adapt_storage(to::$(dev), x::OneElement) = Adapt.adapt(to, collect(x))
end
```

**Review by avik-pal — CHANGES_REQUESTED** [review]

**Review by avik-pal — APPROVED** [review]
