### PR TITLE
fix: try increasing the samples in CI

### LINKED ISSUE #1274: Convolutional VAE for MNIST using Reactant failed to produce right results
The Reactant example in the document failed to produce the right results for the latest version.
[https://lux.csail.mit.edu/dev/tutorials/intermediate/5_ConvolutionalVAE](url)

Image

### PR DESCRIPTION
**Pull request by avik-pal**
strangely enough I cant repro the failure locally

### CODE REVIEW

File: docs/run_single_tutorial.jl [hunk 1]
```diff
@@ -71,9 +87,9 @@ end
 Literate.markdown(
     path,
     output_directory;
-    execute=true,
+    execute=should_run,
     name,
-    flavor=Literate.DocumenterFlavor(),
+    flavor=should_run ? Literate.CommonMarkFlavor() : Literate.DocumenterFlavor(),
```
Comment (avik-pal) [inline docs/run_single_tutorial.jl:92]:
```suggestion
    flavor=should_run ? Literate.DocumenterFlavor() : Literate.CommonMarkFlavor(),
```
